[book]
authors = ["Technology Services"]
language = "en"
src = "src"
title = "Clouds and Platforms"

[output.html]
default-theme = "aggie"
preferred-dark-theme = "navy"
additional-css = ["./theme/css/tabbed-code-blocks.css", "./theme/css/aggie-custom.css"]
additional-js = ["./theme/js/tabbed-code-blocks.js"]
git-repository-url = "https://github.com/tamu-edu/it-cloud-docs"
edit-url-template = "https://github.com/tamu-edu/it-cloud-docs/edit/main/{path}"
# mdBook 0.5 options - disable new sidebar header navigation to maintain current look
sidebar-header-nav = false

[output.html.print]
enable = false

[output.html.fold]
enable = true    # whether or not to enable section folding
level = 0         # the depth to start folding
