#name: Build & Publish
#on:
#  pull_request:
#    types:
#      - closed

#jobs:
#  build-deploy:
#    runs-on: ubuntu-latest

#    steps:
#      - name: Checkout ğŸ›
#        uses: actions/checkout@v2

#      - name: Init
#        run: make init

#      - name: Build ğŸ—ï¸
#        run: make build

#      - name: Deploy to GitHub Pages ğŸš€
#        uses: peaceiris/actions-gh-pages@v3
#        with:
#          github_token: ${{ secrets.GITHUB_TOKEN }}
#          publish_dir: ./book
#          cname: docs.cloud.tamu.edu